// Real admin assets, synthetic API fixtures, no production configuration or calls.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const base = process.env.ADMIN_TEST_URL || 'http://127.0.0.1:8769';
(async()=>{
  const browser = await chromium.launch({headless:true, executablePath:process.env.ADMIN_TEST_BROWSER || undefined});
  try {
    const context = await browser.newContext({viewport:{width:1600,height:1100}});
    const page = await context.newPage();
    const errors=[]; page.on('pageerror',e=>errors.push(e.message));
    const writes=[];
    const vision={enabled:true,provider:'custom',model:'vision-fixture',base_url:'https://example.test/v1',has_api_key:true};
    const ocr={mode:'vision',provider:'glm',api_protocol:'glm_layout_parsing',model:'ocr-fixture',base_url:'',endpoint_url:'https://example.test/layout',has_api_key:true,configured:true,effective:true};
    await page.route('**/*',route=>{
      const url=new URL(route.request().url());
      if(url.origin===base && url.pathname.startsWith('/static/'))return route.continue();
      const path=url.pathname;
      if(route.request().method()!=='GET')writes.push({path,body:route.request().postDataJSON()});
      let body={};
      if(path==='/vision-params')body=vision;
      if(path==='/image-recognition')body=ocr;
      if(path==='/vision-params/phone-control')body={};
      if(path.startsWith('/image-recognition/test/'))body={ok:true,duration_ms:12};
      if(path==='/model-presets')body={presets:{},routing_profiles:{default:{chat:'fixture'}},active_routing:'default'};
      if(path==='/scheduler/config')body={owner_id:'fixture_owner',enabled:true,presence_nag_minutes:60,global_proactive_min_gap_hours:1.5};
      if(path==='/scheduler/status')body={triggers:{}};
      return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
    });
    const cdp=await context.newCDPSession(page);
    await cdp.send('Network.enable');
    await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});
    await cdp.send('Network.clearBrowserCache');
    await page.goto(base+'/static/index.html');
    await page.reload({waitUntil:'networkidle'});
    await page.evaluate(()=>{
      document.getElementById('auth-overlay').style.display='none';
      document.getElementById('app').style.display='flex';
    });
    await page.evaluate(()=>goto('model-routing'));
    await page.locator('#vision-connections-body tr').first().waitFor();
    assert.equal(await page.locator('#vision-connections-body tr').count(),2);
    assert.equal(await page.locator('#vision-general-editor').isVisible(),false);
    await page.locator('[data-action="toggleVisionEditor"][data-action-args=\'["vision-general-editor"]\']').click();
    assert.equal(await page.locator('#vision-general-editor').isVisible(),true);
    await page.locator('#vision-base-url').fill('https://custom.example/v1');
    await page.locator('#vision-provider').selectOption('gemini');
    assert.equal(await page.locator('#vision-base-url').inputValue(),'https://custom.example/v1');
    await page.locator('[data-action="saveVisionParams"]').click();
    await page.waitForTimeout(100);
    assert.equal(writes.at(-1).body.base_url,'https://custom.example/v1');
    await page.locator('[data-action="toggleVisionEditor"][data-action-args=\'["vision-ocr-editor"]\']').click();
    await page.locator('#ocr-protocol').selectOption('chat_completions');
    assert.equal(await page.locator('#ocr-base-field').isVisible(),true);
    assert.equal(await page.locator('#ocr-endpoint-field').isVisible(),false);
    await page.locator('#ocr-base-url').fill('https://ocr.example/v1');
    await page.locator('[data-action="saveImageRecognition"]').click();
    await page.waitForTimeout(100);
    assert.equal('mode' in writes.at(-1).body,false);
    await page.locator('#image-recognition-mode').selectOption('ocr');
    await page.locator('[data-action="saveImageRoute"]').click();
    await page.waitForTimeout(100);
    assert.deepEqual(writes.at(-1).body,{mode:'ocr'});
    await page.locator('[data-action="testImageConnection"]').first().click();
    await page.waitForTimeout(100);
    assert.match(await page.locator('#vision-test-general').innerText(),/12 ms/);
    // A parameterized reverse translation must never split English technical labels.
    await page.evaluate(()=>{
      const el=document.createElement('p');el.id='translation-regression';el.textContent='Tool Loop';
      document.getElementById('page-model-routing').append(el);
    });
    await page.waitForTimeout(100);
    assert.equal(await page.locator('#translation-regression').innerText(),'Tool Loop');
    await page.screenshot({path:'.tmp/admin-model-routing.png',fullPage:true});
    await page.locator('#admin-language-select').selectOption('en');
    await page.getByText('Presets · Image connections',{exact:true}).waitFor();
    assert.equal(await page.getByText('Routing · Image purposes',{exact:true}).isVisible(),true);
    await page.locator('#admin-language-select').selectOption('zh-CN');
    await page.getByText('Presets · 图像连接',{exact:true}).waitFor();
    await page.evaluate(()=>goto('scheduler'));
    await page.locator('#sc-presence-minutes').waitFor();
    assert.equal(await page.locator('#sc-owner-id,#sc-signatures').count(),0);
    await page.locator('[data-action="saveSchedulerConfig"]').click();
    await page.waitForTimeout(100);
    assert.equal('owner_id' in writes.at(-1).body,false);
    assert.equal('signatures' in writes.at(-1).body,false);
    await page.evaluate(async()=>{await loadPageFragment('autonomy-settings');document.querySelectorAll('.page.active').forEach(el=>el.classList.remove('active'));document.getElementById('page-autonomy-settings').classList.add('active');});
    const cards=page.locator('.autonomy-source-grid > .card');
    const boxes=await Promise.all([0,1,2].map(i=>cards.nth(i).boundingBox()));
    assert.equal(boxes[0].x,boxes[1].x);assert.equal(boxes[1].x,boxes[2].x);
    assert.ok(boxes[0].y+boxes[0].height<=boxes[1].y);
    assert.ok(boxes[1].y+boxes[1].height<=boxes[2].y);
    assert.equal(await page.getByText('允许活动的开始时间',{exact:true}).isVisible(),true);
    await page.screenshot({path:'.tmp/admin-autonomy.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    await page.screenshot({path:'.tmp/admin-autonomy-mobile.png',fullPage:true});
    assert.deepEqual(errors,[]);
    console.log('Admin settings browser checks passed (desktop and narrow screen, cache disabled).');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
